### ISSUE TITLE
snnls: double addition of regularization term

### ISSUE THREAD

**Issue by stestoll** [JeschkeLab/DeerLab#103]
As noted by @mtessmer, `ResidualFcn` in `snnls.py` seems to be adding the regularization term twice, once prior to calling `_augment`, and then again in `_augment` itself. It should only be once.

Here is the place in ``snnls.py``:
```python
if includePenalty:
    penalty = alpha*L@linfit
    # Augmented residual
    res = np.concatenate((res, penalty))     #    <---  first addition
    res, _ = _augment(res, [], regtype, alpha, L, linfit, huberparam, Nnonlin)    #   <---- second addition
```

**Comment by luisfabib** [comment]
I already have applied the appropiate changes on my local copy. After I run a couple of checks, a PR will follow tomorrow.
