### ISSUE TITLE
correctphase prone to inverting signal.

### ISSUE THREAD

**Issue by mtessmer** [JeschkeLab/DeerLab#114]
Using deerlab.correctphase inverts the attached nutation experiment.

[Nutation.zip](https://github.com/JeschkeLab/DeerLab/files/6199969/Nutation.zip)

```python
import deerlab as dl
import matplotlib.pyplot as plt
t, V = dl.deerload('Nutation.DTA')
Vph = dl.correctphase(V)
Vtrue = -Vph

plt.plot(t, V, label='Raw Data')
plt.plot(t, Vph, label='DeerLab Phased')
plt.plot(t, Vtrue, label='Correctly Phased')
plt.legend()
plt.show()
```

![Nutation](https://user-images.githubusercontent.com/18681246/112372640-46c4f880-8c9d-11eb-8668-2412f1348807.png)

**Comment by stestoll** [comment]
In this particular example, the raw data already is inverted (blue trace), and `correctphase` changes it just minimally by about 7 degrees (orange trace).

The basic assumption of `correctphase` is that the signal is more or less phased as desired, and only small adjustments need to be done. `correctphase` performs a least-squares minimization of the phase, minimizing the norm of the imaginary component, and using the average phase of the raw data as a starting point.

Should we adjust this behavior?

**Comment by mtessmer** [comment]
It could be useful to change the behavior for scripted data sets that do not allow users to set the phase. This nutation experiment was run as part of a prodel script and the phase changes as the script progresses

**Comment by stestoll** [comment]
Indeed, the norm of the imaginary part has two minima as a function of phase angle, so the solution provided by `correctphase` is not unique - if there is a minimum at `ph`, then there is one at `ph+pi` as well.

The current approach picks the minimum closest to zero phase angle. Instead, as @mtessmer suggests, `correctphase` could pick the minimum with the larger integral of the real part of the phased signal.

We could implement this as new default behavior, with a keyword argument to switch it off. For example: `selphase=maxrealint` for the new (default) behavior, and `selphase=minphase` for the current behavior.

**Comment by stestoll** [comment]
This keyword argument was eliminated in https://github.com/JeschkeLab/DeerLab/commit/3d0919c739f15645ee609273552612e20920c25c. The function returns the minimizer phase that yields a positive average of the real part.
