### ISSUE TITLE
Issue with error band scaling when using FitResult.plot() 

### ISSUE THREAD

**Issue by mtessmer** [JeschkeLab/DeerLab#132]
Error bands do not seem to scale properly with the experimental signal when plotting via the FitResult.plot() method.

```python
import numpy as np
import deerlab as dl

r = np.linspace(1.5, 8., 256)
t = np.linspace(-0.2, 4.5, 256)
B = dl.bg_hom3d(t, 80)
K = dl.dipolarkernel(t, r, pathways=0.6, B=B)

P = dl.dd_gauss(r, (4., 0.2))
V = K@P + np.random.normal(0, 0.005, len(t))

fit = dl.fitmodel(V, t, r)
fit.plot()

V *= 1e6
fit = dl.fitmodel(V, t, r)
fit.plot()
```

![image](https://user-images.githubusercontent.com/18681246/113069764-e68af680-9175-11eb-9ffb-c090be5df4be.png)
![image](https://user-images.githubusercontent.com/18681246/113069777-ebe84100-9175-11eb-9afc-31aaee5637dd.png)

**Comment by luisfabib** [comment]
The strange behavior is that this issue (in your example) occurs if I set large values above `1e5` but with values below `1e4` does not happen. There must be some numerical bug happening with these large values.
