### ISSUE TITLE
fitmodel: incomplete support for regularization customization

### ISSUE THREAD

**Issue by stestoll** [JeschkeLab/DeerLab#135]
Currently, `fitmodel` provides access to the regularization type via the `regtype` keyword. However, it gives not access to the regularization order (`regorder` in `fitregmodel`) and other regulariztion settings such as the Huber parameter and OBIR parameters.

I don't think it makes sense to only partially support regularization customization in `fitmodel`.

I suggest we remove the `regtype` keyword argument from the `fitmodel` interface and hardwire `'tikhonov'` into the function call of `fitregmodel` inside `fitmodel`.

This solves the other (smaller) issue that the current default `regtype='regparam'` is not functional when used with parametric distance distribution models.

If needed, full regularization control can be added to `fitmodel` in a future release, once the regularization settings are aggregated into an object.

**Comment by luisfabib** [comment]
Agreed, `regtype` should be removed as an option from `fitmodel`. 

Anyway `fitmodel` should be a top-level function, and such detailed functionality should be only available at low-level usage of DeerLab.
