### ISSUE TITLE
Documentation: add images to distance distributions for better illustrations.

### ISSUE THREAD

**Issue by spribitzer** [JeschkeLab/DeerLab#180]
I think it might be nice to add some figures to the various `dd` distributions in the documentation. 
This would be particular helpful in the case of some of the more "exotic" distributions like rice, or triangle.

Currently, equations are shown and the individual parameters are listed in a table. It would be really nice to also have these illustrated in form of a figure. 

Additionally, I noted that there is an image showing up for randcoil. But it is very small and barely readable:
![image](https://user-images.githubusercontent.com/12035048/120042934-ebc2c100-bfbf-11eb-8e51-93d7af38695b.png)

**Comment by luisfabib** [comment]
I agree that it would be ideal. But for now, hand-drawing a schematic figure for each model in the program is too time-consuming, and we have bigger fronts to invest time into. 

External PRs are most welcome. Otherwise, I will close this issue. 

The image issue was fixed in some previous commits.
