### ISSUE TITLE
[CONSISTENCY] Rice distributions still use sigma

### ISSUE THREAD

**Issue by gjeschke** [JeschkeLab/DeerLab#19]
Whereas all other parametrized distance distributions use full width at half maximum (FWHM) as a width parameter, Rice distributions still use the standard deviation of their Gaussian factor.

**Comment by gjeschke** [comment]
Dear Stefan,

> I don't think the sigma parameter in the Rice distribution should be called "standard deviation"

well, if you read carefully, I called it "standard deviation of the Gaussian factor", which it is. It is not the standard deviation of the total distribution.

> The question then is, should we parameterize dd_rice and all other distribution models via their mathematical parameters (r0, sigma), or via their properties (mode, mean, FWHM). For a Gaussian, these two parameterizations are the same, but not for any of the other distributions.

Well, the origin of this issue is that I asked Luis whether the FWHM parametrization is a stable feature of DeerLab. I am just specifying restraint syntax for MMMx and want to be consistent with DeerLab (see control_files.html at https://github.com/gjeschke/MMMx for the current specs).

I have to admit that I do not believe in frequent re-specification, but rather in stable software. Once I have implemented the control file reader (starting tomorrow, probably completed before next Thursday) it will require very good arguments in order to convince me that I should change it.
Once the first MMMx version is out, no way I will change specifications for aesthetic reasons.

(I preferred to keep this e-mail private between us, rather than answering in full on GitHub).

Kind regards

Gunnar

---

Der Schlaf der Vernunft gebiert Ungeheuer - Francisco Goya

Prof. Dr. Gunnar Jeschke
ETH Zurich
Department of Chemistry and Applied Biosciences
Vladimir-Prelog-Weg 2
CH-8093 Zurich Switzerland

www.epr.ethz.ch

________________________________________

**Comment by stestoll** [comment]
I am open to abandoning FWHM in favor of sigma in Gaussian distance distributions, for the sake of consistency with Rice.

**Comment by luisfabib** [comment]
> I am open to abandoning FWHM in favor of sigma in Gaussian distance distributions, for the sake of consistency with Rice.

Equivalently, we could just reformulate the Rice parameters to use the Gaussian FWHM instead of the standard deviation.

As Gunnar mentioned above, the Ricians take the **standard deviation of the underlying Gaussian distributions, not the true standard deviation of the Rician distribution**. 

Therefore, we could easily just reformulate that into the FWHM as we do in the Gaussians. This way everything would be consistent.

**Comment by stestoll** [comment]
I am not sure this is a good idea. The idea of FWHM for a Gaussian is that it relates directly to the visual appearance of the distribution, but this is not accurate for a Rice. I am leaning towards `sigma` for both Gaussian and Rice.

**Comment by luisfabib** [comment]
In that case I assume that in the Rice case by `sigma` you refer to the actual standard deviation of a Rice distribution, and not the the actual parameter in DeerLab which is the standard deviation of the underlying Gaussian. That would be consistent, but the problem is that the actual Rice standard deviation depends on both the center and width parameters of the Gaussian distribution. We would find another parameter to determine the position of the Rice that does not depend on the Rice width.

**Comment by stestoll** [comment]
No, I mean the mathematical `sigma` parameter.

**Comment by gjeschke** [comment]
I also have a slight leaning to using the mathematical parameters for all distributions. This provides consistency and, as the expressions are in the docs, it is unambiguous. It is applicable to any distribution function one might want to add in the future.

If one wants a general characterization, one should have a function for moment analysis: first moment is the mean value, second central moment the standard deviation, third central moment is skewness (beyond that, it is not expected to be meaningful anyway). Any distribution, including parameter-free ones, could be analyzed by this function.

**Comment by luisfabib** [comment]
Ok, in that case we will set for `sigma` as width parameter instead of the FWHM for the Gaussian distributions. I will implement this. This might take a bit of time as all tests depend on the Gaussian distributions and will have to manually adapt the width values for the new parameter.

**Comment by gjeschke** [comment]
No hurry. Realistically, I can implement the modelling modules of MMMx only starting in mid-September and for the control file reader I only need the specification decision, not a workable implementation in DeerLab.

**Comment by luisfabib** [comment]
The width parameters of the Gaussian models used in the examples and documentation still need to be adjusted to the recent changes.
