### ISSUE TITLE
Memory consumption of DeerLab

### ISSUE THREAD

**Issue by luisfabib** [JeschkeLab/DeerLab#201]
Some DeerLab functions, a particular example being `dipolarkernel`, can be extremely memory-demanding under certain circumstances. 

For example, calling 
```python 
t = np.linspace(-1,7,1000)
r = np.linspace(3,6,500)
dipolarkernel(t,r,method='grid') # by default 5001 grid knots 
```
leads to a 16GB RAM WinOS system to run out of memory and fully freeze.  

A solution either to the memory costs or limiter to the memory consumption must be implemented to avoid freezing the whole OS by a DeerLab call.

**Comment by stestoll** [comment]
Besides `dipolarkernel` in the above example, which other functions create memory issues?

**Comment by luisfabib** [comment]
The bootstrap analysis `bootan` could also be another potential memory pit, depending on the number of bootstrap samples being taken and the size of the vectors being bootstrapped.

**Comment by luisfabib** [comment]
Also certain Numpy operations (in my experience) with the MKL can hoard as much resources as they can to speed up the operations.
