### ISSUE TITLE
`docs/beginners_guide`: Latex equation not rendering

### ISSUE THREAD

**Issue by luisfabib** [JeschkeLab/DeerLab#206]
![image](https://user-images.githubusercontent.com/48292540/126938683-7a8ddfee-18f4-47db-8969-fa6782e1a200.png)

**Comment by kadatatlukishore** [comment]
Hey @luisfabib , Can I work on this?

**Comment by luisfabib** [comment]
Hi @kadatatlukishore, sorry I had forgotten to push the changes (it was a very small typo). 

Thanks for the comment and feel to contribute any PRs in the future! ;)

**Comment by kadatatlukishore** [comment]
Thanks @luisfabib
