### ISSUE TITLE
fitmultimodel is no longer deterministic 

### ISSUE THREAD

**Issue by luisfabib** [JeschkeLab/DeerLab#22]
With the changes introduced in 05f304e the results of `fitmultimodel` are no longer deterministic as the parameter start values are changed randomly between runs. This has some disadvantages: 

- Reproducibility is broken if the results do not correspond to a global minimum found by multi-start approaches. 
- Testing can become an issue if pass conditions are tight.
- Future bugs or issues related to this randomness can become a high nuisance to debug.

My proposal would be to redefine the way the start values of `fitmultimodel` are computed, e.g. setting them to the center of the box constraints or at intervals of those.

**Comment by stestoll** [comment]
Three options for `fitmultimodel`:
- Just document that it uses random start points.
- Implement deterministic start points, such as a grid over the parameter space.
- Implement a more advanced global-search strategy.
