### ISSUE TITLE
Fitting a background-only trace with `fitsignal` fails if scale is not 1

### ISSUE THREAD

**Issue by stestoll** [JeschkeLab/DeerLab#26]
The following script shows that `fitsignal` is not able to fit a background-only signal with scale different from 1. This should work.

```python
import numpy as np
import matplotlib.pyplot as plt
import deerlab as dl

t = np.linspace(0,5,100)
r = np.linspace(2,6,200)
B = 42*dl.bg_exp(t,0.2)

fit = dl.fitsignal(B,t,r,None,dl.bg_exp,dl.ex_4pdeer,uqanalysis=False)

plt.plot(t,B,t,fit.B)
```

**Comment by luisfabib** [comment]
There was a minor bug related to this (see fix 159342c and b46d10d), but the fit is actually working.

I get the following fit parameters:
````
lam:  0.001
kappa:  200
scale: 42
````
which completely sense. The actual fit is `fit.V` not `fit.B`. Think about the model: 
````
V = V0*(1-lam)*B
````
what you are actually calling `B = 42*dl.bg_exp(t,0.2)` should be `V = 42*dl.bg_exp(t,0.2)`. In the model you are fitting `B = dl.bg_exp(t,kappa,lam)` and `V0*(1-lam)=42`.

So it makes sense that `fit.B` returns the background decay function (unscaled). The primary signal is the scaled background with the unmodulated component of the DEER signal. 

Here is the fit:

![Figure_1](https://user-images.githubusercontent.com/48292540/93577898-ea56e880-f99c-11ea-839e-c627918ee53e.png)
