### ISSUE TITLE
Deprecate `correctscale`

### ISSUE THREAD

**Issue by luisfabib** [JeschkeLab/DeerLab#272]
In the context of the new system introduced in v0.14.0, the function `correctscale` serves no purpose whatsoever. The function just performs a rescaling of a dipolar signal based on a basic analysis (which is already limited to the single-pathway 4-pulse DEER model) and nothing more. The new modeling and fitting system does always automatically account for the scaling factor of the data for any kind of model (parametric or nonparametric). 

From my point of view, this is a derelict of the older versions and serves no further purpose.

**Comment by stestoll** [comment]
Indeed, `correctscale` serves no function now that the overall signal amplitude is included in the model.

**Comment by stestoll** [comment]
Another problem is that non-parametric fit currently does not return a scale. See #284 .

**Comment by luisfabib** [comment]
> Indeed, `correctscale` appears superfluous now that the overall signal amplitude is included in the model. But it is one of the three nuisance instrumental parameters (with phase and time shift) that many consider outside the physics model.
> 
> If we eliminate this function, then to be consistent we would have to eliminate the other two as well and include phase into the model.

Not really. I see why one could delete `correctzerotime`, since we actually now include by default the refocusing times in the model even for a single pathway model. It may however, still be useful to estimate the zerotime when there is no information about the experiment time delays. 

In the case of the `correctphase` function, there is no reason to delete it. The function is useful even outside of dipolar EPR applications. I know of DeerLab users that apply it for other fields that need this kind of phase correction. Even for dipolar EPR, it is useful to optimize the phase and just work with the real part of the signal, even though the program can handle complex signals.

**Comment by luisfabib** [comment]
However, the `correctscale` function is truly superfluous and it even works using a very specific model to estimate the scaling factor (a single pathway model of 4-pulse DEER with a single Gaussian distance distribution). For example, `correctphase` is truly fully general.

**Comment by stestoll** [comment]
Okay.
