### ISSUE TITLE
deerload parameters

### ISSUE THREAD

**Issue by ecanarie** [JeschkeLab/DeerLab#29]
With 0.10, I was able to use deerload with:

`t, V, parms = dl.deerload('20200828_41R1_211R1_apoMBP_4PDEER_50K_PhSUM.DTA')`

In version 0.11, I get this error unless I get rid of `parms`:
`ValueError: not enough values to unpack (expected 3, got 2)`

**Comment by mtessmer** [comment]
`deerload` now allows you to specify a boolean `full_output` option which will return `t, V, params`:

```python
t, V, parms = dl.deerload('20200828_41R1_211R1_apoMBP_4PDEER_50K_PhSUM.DTA', full_output=True)
```
otherwise, it does not return params by default:

```python
t, V = dl.deerload('20200828_41R1_211R1_apoMBP_4PDEER_50K_PhSUM.DTA')
```
