### ISSUE TITLE
DeerLab does not conform to the PEP8 style guide

### ISSUE THREAD

**Issue by mtessmer** [JeschkeLab/DeerLab#306]
[PEP8](https://peps.python.org/pep-0008/) outlines style guidelines for python to improve readability and usability. DeerLab does not currently conform well to PEP8 making it difficult to read and often limiting functionality. One of the major violations is the excessive use of lambda functions. Overuse of lambda functions is discouraged by PEP8 and, more importantly, prevents other objects (functions included) from being pickled which prevents DeerLab functions from being used by parallelization libraries like multiprocessing. 

Requiring standardized styling will make code more accessible to many contributors and aid others in submitting high-quality contributions. A large portion of making DeerLab compatible with PEP8 can probably be done using packages like `black` or `flake8`.

**Comment by luisfabib** [comment]
I have to admit that I was aware of this. My formatting religion clashed with some of the formatting choices implemented in `black` or imposed by the PEP8. However, I agree that the transition from MATLAB to Python might have led to the inheritance of the overuse of the lambda functions.  As you mentioned, this causes issues with pickling and makes debugging (mainly for other contributors) particularly hard (as all lambda functions appear as __lambda__ in the calltree). 

I think I am at a point ready to lean more into the PEP8 formatting and rely more on `flask8` linting and the `black` formatted. As you said this will boost productivity and quality of future contributions and even fix some current issues such as the pickling of functions.

**Comment by stestoll** [comment]
I think `black` is great. Main problem is that if we run it on the entire code base and commit, it is going to distort line histories. So I thibk we should slowly incorporate the formatting only in places where we do functional edits.

`lambda` vs `def`: I think this is one of the recommendations in PEP8 that we should ignore. `lambda`s are fine - they are more compact that `def`s and generate identical bytecode.

I don't see why using a formatter increases productivity. As is, the code base is nicely formatted. We`ve got more important things to do.

One of them is figuring out whether function call overheads are performance relevant anywhere. If yes, functions (particularly nested ones) should be eliminated. Right now, we are using `lambda` defs quite a bit for partial function wrappers. Would be great to see some of those eliminated.

**Comment by luisfabib** [comment]
I do not agree with your `lambda` vs `def` view. I think this is an actual bug in the program. For example, currently, you cannot save the output object of a DeerLab fit to a file, load that file, and compute the confidence intervals due to the  `ci` lambda function not being correctly pickled. Also, it is pretty exhausting when debugging, and you have to sort over 10 different `__lambda__` object calls in the calltree.  

Of course, they are compact, and that's why I also would prefer them for short function assignments, particularly when passing them to functions. PEP8 does not demonize the use of `lambda` functions; it discourages assigning `lambda` functions to variables. 

I have been running `black` and `flask8` through many of DeerLab files, and while I really like the current formatting, it seems to be quite inconsistent, particularly in terms of spacing, type checking, and function definitions.  

I do not know at this moment whether a distortion of the line histories is enough argument to not introduce a formatting change throughout. Maybe @mtessmer can comment a bit further (after all he's the Python expert in our development group).

**Comment by luisfabib** [comment]
Now, I think this will need to be addressed after the release of v0.14.0 which is (almost) complete.

**Comment by mtessmer** [comment]
I agree with @stestoll that a lump sum overhaul with `black` would be a bad idea but, I think @luisfabib has brought up even more good reasons to get rid of `lambda` funcs. Perhaps a PEP8 requirement for new commits going forward and making the removal of persistent lambdas a milestone for something like 0.14.1? I recommend installing a PEP8 linter in VS Code or using an IDE like PyCharm that has a PEP8 linter built-in.

**Comment by luisfabib** [comment]
I am working on implementing a pre-commit or GHA workflow that runs `black` and then `flask8` over changed files in a PR. This will slowly refactor DeerLab into compliance with PEP8. @stestoll mentioned the possibility of linting and formatting just changed lines in a commit (basically linting the git diff). This is not possible with `flask8` and `black` as they both operate on files and AFAIK do not allow linting of specific code blocks.

**Comment by luisfabib** [comment]
I tried implementing `darker` to linting and formatting to the lines changes in a PR, however, I cannot make it work properly with `pre-commit` to apply automatically the changes and commit them. If we want `darker` to just notify of PEP8 issues then we could use it. Contributors would then have to run `black` or `darker` locally and push the properly formatted changes.

**Comment by luisfabib** [comment]
I managed to get a GHA to run with `darker` (https://github.com/akaihola/darker). This package checks the `git diff` between two states in the `git history` and then runs `black` formatting and `flake8` linting to the lines changed in the `git diff`. This should be exactly what we need. With this workflow, now every new line added or changed in a commit in a PR will be formatted into compliance with PEP8 and additional PEP8-related issues will be caught by the linter and reported. 

This will allow us to slowly refactor DeerLab into PEP8 compliance without the need to fully refactor the whole code base at once.
