### ISSUE TITLE
Simplify branching workflow

### ISSUE THREAD

**Issue by stestoll** [JeschkeLab/DeerLab#32]
The current [branching workflow](https://medium.com/@patrickporto/4-branching-workflows-for-git-30d0aaee7bf) is based on the Git flow.

I suggest we move to a simpler model (GitHub flow), with the following setup:
- The default branch is called `main` and contains the current bleeding-edge code that should be deployable.
- Small bugfixes and improvements go directly to `main`.
- For new features and bigger refactoring, use feature branches and PRs.
- For releases, tag with a release number and start a new release branch, e.g. `v0.12.0`.

GitHub is [renaming the default branch from `master` to `main`](https://github.com/github/renaming) We should follow this as well.

**Comment by luisfabib** [comment]
We have switched to the GitHub flow model. `main` is now the default branch with the deployable source code. 

For the moment (at least), the GH-Pages deployment has been set run upon new releases rather than commits to `main`.
