### ISSUE TITLE
Provide distance mean etc

### ISSUE THREAD

**Issue by stestoll** [JeschkeLab/DeerLab#33]
Currently, the user has to explicitly calculate the mean distance via  `r_mean = np.sum(r*fit1.P*(r[1]-r[0]))` (or something more sophisticated). Same for the distance mode and median.

It would be quite useful if a DeerLab fit can provide basic statistics about the distance, such as the mean and modal distance, including uncertainty estimates for all these quantities.

This could be in the form of a function that takes `r` and `P` as input and returns these values, including uncertainties. Or it could be integrated into the fit functions.

```

**Comment by luisfabib** [comment]
I have implemented `distdesc.py` (commit f3d3d89), a function which takes a distance distribution (and its uncertainty) and returns a whole set of parameter descriptors of the location, spread and shape of the distribution along their uncertainty (via covariance propagation). 

The function is ready to be PR to the `main` branch.

**Comment by stestoll** [comment]
This looks good. I did some small edits. Please open a PR for the `distribution_descriptors` branch, so we can discuss there further improvements.

**Comment by stestoll** [comment]
Implemented with 5a9915f534a6fc2f684b1abafccc35d39ed93d6c
