### ISSUE TITLE
Simplify parameter boundaries interface for fisignal

### ISSUE THREAD

**Issue by luisfabib** [JeschkeLab/DeerLab#40]
Another remnant of the old MATLAB interface. In `fitsignal` the lower/upper boundaries of the different parameter subsets are specified as a single keyword
````python
fitsignal(__, lb = [lb_dd,lb_bg,lb_ex], ub = [ub_dd,ub_bg,ub_ex])
````
Since one seldom needs to re-define all boundaries for all subsets, it would make sense to simplify this to multiple keywords
````python
fitsignal(__, lb_dd = lb_dd, lb_bg = lb_bg lb_ex = lb_ex)
````
this way a quick assignment can be done without needing to worry about the order of the parameter subsets.

**Comment by stestoll** [comment]
This sounds reasonable, and is consistent with the existing interface where the three models are already provided separately. To be completely consistent, this must be extended to the starting parameter `par0` -> `par0_dd`, `par0_bg`, `par0_ex`. So the choice is between two extremes:
- `model`, `par0`, `lb`, `ub`
- `model_dd`, `model_bg`, `model_ex`, `par0_dd`, `par0_bg`, `par0_ex`, `lb_dd`, `lb_bg`, `lb_ex`, `ub_dd`, `ub_bg`, `ub_ex`

The second approach has the downside that it has a large number of keyword arguments. Maybe there is another way of organizing all these inputs. Group par0, lb, and ub for each model together? Or for each parameter?

**Comment by luisfabib** [comment]
After some consideration it seems that the second approach will be the most pythonian way of dealing with this. Having multiple keyword arguments with explicit names instead of a single keyword with nested lists and implicit ordering seems to align very well with the [PEP20](https://www.python.org/dev/peps/pep-0020/#references) guideline. 

This will make the function call much readable only at the cost of more keywords to document. A PR will follow soon.
