### ISSUE TITLE
DeerLab Installation on Mac with Apple M1 Chip fails

### ISSUE THREAD

**Issue by BeneshJ** [JeschkeLab/DeerLab#407]
DeerLab installation fails on Mac with Apple M1 chip. The issue seems to be more connected with the installation of the cvxopt package. Trying different versions of the NumPy (in combination with cvxopt) also didn't work. Has anyone got a workaround?

**Comment by luisfabib** [comment]
I'm aware. I have seen this issue in our lab. The cvxopt people have not updated their backend to work with the new M1 chip. For now I have not found any workaround for those specific cases. However, in the coming major update to DeerLab (coming very soon) we will remove the strict dependency on cvxopt to avoid this kind of issue.

**Comment by luisfabib** [comment]
For now the best I can recomend is to work with the development version. Either with at the head of `main` or at commit 64e03821ae82d1623c41c64e418714b02cede97c where we introduced the change to avoid the strict use of cvxopt.

**Comment by BeneshJ** [comment]
Many thanks! Will try that
