### ISSUE TITLE
Regularization selection output should be accessible from the fit object. 

### ISSUE THREAD

**Issue by mtessmer** [JeschkeLab/DeerLab#412]
Currently, FitResult returns some stats like AIC, BIC, AICc, etc. but these do not appear to be the scores for the (smoothness) regularization parameter, which is a bit confusing. To the best of my knowledge the regularization parameter selection criteria value is inaccessible from the FitResult object.  This hinders investigating under and over-smoothing artifacts. Additionally, this makes it very difficult to generate L-curves or "regularization parameters selection criteria" surfaces. This information could be valuable as supplementary data for publication like the L-curve once was. regularization parameter selection criteria should be accessible from the fit object, and maybe even re-evaluatable for a given set of nonlinear parameters to generate L-curves and the like.

**Comment by HKaras** [comment]
I agree that more infomation about the regularisation parameter selection would be useful, especially if you are having stuggles selecting the correct regularisation parameter.

**Comment by HKaras** [comment]
I have started to investigate the best way of exposing this infomation to the user in the FitResult class.

Would it be of interest to have the regularisation selection output for every call of the least squares optimiser or just the final one? 

I suspect the final one would be enough in nearly all cases but sometimes it might be useful to have all.

**Comment by mtessmer** [comment]
iirc most of the stored metrics are only for the final least squares optimization, in which case I think that it would be consistent to report just the final one. That being said, it may be time to expand FitResult to include some methods for exploring some of these parameters, e.g. a method to make an L-Curve, though this should probably be discussed in a separate issue.

**Comment by HKaras** [comment]
I think it would be most consistent if only the data is passed to FitResult and there are no additional methods. Adding additional methods to FitResult is a significant design change, and something that we should decide separately. 

I think a decent example is sufficent, this also gives the oportunity to explain the use of the L-Curve and functionals a bit more. 

This is the approach I have taken in my draft pull request.
