### ISSUE TITLE
Documentation issues and a mistake in code

### ISSUE THREAD

**Issue by sergeqzin** [JeschkeLab/DeerLab#434]
Dear DeerLab team,

please note some corrections to the documentation proposed by me. In addition, there is a small mistake found in `dd_models.py`. Everything is described in the attached file.

Thank you

[DeerLab documentation issues.docx](https://github.com/JeschkeLab/DeerLab/files/12260726/DeerLab.documentation.issues.docx)

**Comment by stestoll** [comment]
Thanks for this detailed feedback! PR #435 addresses all of the issues you found.
