### ISSUE TITLE
(custom) ex_models

### ISSUE THREAD

**Issue by ritsch-i** [JeschkeLab/DeerLab#44]
Dear DeerLab developers, here goes my first official issue (finally now via git, sorry again, Luis, for annoying you previously via other channels):  

I think future users might be happy if the documentation on the usage of the `ex_models` would be extended a bit more. In particular, I was writing a model for a high-spin RIDME experiment, and it took me a while (admittedly being rather new to python) to figure out what the main requirements of an experiment are, in terms of what a newly written experiment must fulfil, e.g. whether it is possible to pass parameters to the experiment (I know now that it is not), how the program knows how many arguments are required, ... I realise this will probably not be a heavy-use functionality by most future users, but it is a very unique feature of DeerLab to be able to define completely custom pathways during experiments, so it might be worth documenting well :) 

Feature request (?):  continuing on this, it would actually be great if constant parameters could be passed on to the ex_models when they are being used in `fitsignal`. Otherwise even quite simple modification of the Deer-Kernel, like adjusting for the g-values, or including (fixed-value) harmonics need to be hard-coded (annoying and error-prone), or fitted via a custom routine (which I find less intuitive to use).  

P.S. sorry, while I am familiar with the concept and general principles of version control via github, but I am shamefully unexperienced with actually using it, especially in collaborations, so please don't hesitate to point out when I'm doing something wrong 

Cheers, Irina

**Comment by luisfabib** [comment]
There are different issues here: 

- Regarding documentation of `ex_` models. The `ex_` models are not supposed to be employed as user-defined models. These are only bottom-level models built-in into the software. The intended way when wanting to fit new models is to just define these models as functions and passing them to the appropriate fit functions. 
- Related to this is the fact that `fitmodel` (previously `fitsignal`) does not accept custom models. This is also intended. This function implements a very specific physical model and allowing custom models might break that model. Custom models can be fitted by any of the other fit functions in DeerLab. 
- Regarding your feature request. We are also aware that the built-in parametric models in DeerLab are currently somewhat "stiff". It is not possible to fix parameters easily without having to define custom functions, for example. We are considering an overhaul of our model design for a future release, so your request might get fulfilled in the future.
