### ISSUE TITLE
Documentation example bug `fitparamodel`

### ISSUE THREAD

**Issue by ritsch-i** [JeschkeLab/DeerLab#47]
I think the `fitparamodel` example in the documentation has a bug:

In all examples the 'Vmodel' fuction at the point where the actual fit is calculated has an invalid call to np resp. newaxis (see bold below). I'm not sure what the actual code is supposed to be, I am guessing this ensures that the background has the same dimensions as the rest, so maybe `np.newaxis`??  However, if I use the latter instead, I still get (a different) errormessage (see below Vmodel):

**example code from `fitparamodel`[documentation](https://jeschkelab.github.io/DeerLab/functions/fitparamodel.html?highlight=newaxis)**
def Vmodel(par):
    # Extract parameters
    rmean,fwhm,lam,conc = par
    B = bg_hom3d(t,conc)
    P = dd_gauss(r,[rmean,fwhm])
    V = (1-lam + lam*K0@P)***B[:,np,newaxis]**
    return V

**lowest level error code, when changing `np,newaxis`to `np.newaxis` in the example above**
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/deerlab/fitparamodel.py in lsqresiduals(p)
    161 
    162         # Check if there are invalid values...
--> 163         if any(np.isnan(Vsim)) or any(np.isinf(Vsim)):
    164             res = np.zeros_like(Vsim) # ...can happen when Jacobian is evaluated outside of bounds
    165             return res

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by luisfabib** [comment]
This seems to be an old copy-paste error that has gone undetected for being in a docstring. The example can be fixed by just deleting the brackets. 

Example 1: 
````diff 
K0 = dl.dipolarkernel(t,r)
def Vmodel(par):
    # Extract parameters
    rmean,fwhm,lam,conc = par
    B = dl.bg_hom3d(t,conc)
    P = dl.dd_gauss(r,[rmean,fwhm])
--- V = (1-lam + lam*K0@P)*B[:,np,newaxis]
+++ V = (1-lam + lam*K0@P)*B
    return V

# par: rmean fwhm lam conc
par0 = [3.5, 0.5, 0.2, 250] # start values
lb   = [ 1,  0.1,  0,  50 ] # lower bounds
ub   = [20,   5,   1,  800] # upper bounds
fit = dl.fitparamodel(V,Vmodel,par0,lb,ub)
````
Example 2: 
````diff 
K1 = dl.dipolarkernel(t1,r)
K1 = dl.dipolarkernel(t2,r)
def Vmodel(par):
    # Extract parameters
    rmean,fwhm,lam1,lam,2conc = par
    B = dl.bg_hom3d(t,conc)
    P = dl.dd_gauss(r,[rmean,fwhm])
---V1 = (1-lam1 + lam1*K1@P)*B[:,np,newaxis]
---V2 = (1-lam2 + lam2*K2@P)*B[:,np,newaxis]
+++V1 = (1-lam1 + lam1*K1@P)*B
+++V2 = (1-lam2 + lam2*K2@P)*B
    return V

# par: rmean fwhm lam1 lam2 conc
par0 = [3.5, 0.5, 0.2, 0.3, 250] # start values
lb   = [ 1,  0.1,  0,   0,  50 ] # lower bounds
ub   = [20,   5,   1,   1,  800] # upper bounds
fit = dl.fitparamodel([V1,V2],Vmodel,par0,lb,ub)
````
A patch will follow shortly.
