### ISSUE TITLE
set parameter search resolution in `fitparamodel`

### ISSUE THREAD

**Issue by ritsch-i** [JeschkeLab/DeerLab#48]
Wishlist entry :) 

Would be nice to have an option to set the resolution of individual parameters in a parametric model fit with `fitparamodel`. 
Should either be in percent of the upper bound value, and/or individually set for each entry in parameter varible (since they might have comepletly different ranges, e.g. dimensionality, and pathway contribution).

**Comment by luisfabib** [comment]
Being able to specify the resolution of parameters in LM-based non-linear least-squares is not possible as the algorithmic search in parameter space is not performed based on a grid. The convergence criteria such as tolerance in a change of the objective function or in parameter values are the ones controlling the outcome of the fit. Even in the latter case, the change in parameter values is taken in a normalized way such that the absolute values of the parameters should have little or no influence on the outcome of the fit.  

Nevertheless, this issue has revealed a lack of exposure of convergence criteria in some functions (see #111).
