### ISSUE TITLE
pip installation fails in a least-privilege system

### ISSUE THREAD

**Issue by luisfabib** [JeschkeLab/DeerLab#52]
When trying to install DeerLab via 
````
pip install --user deerlab
````
on a cluster with only user-level privileges.

The ``setup.py`` script crashes when trying to install all other dependencies in the installation script: 
````python
# Custom OS-specific installation script
def install_dependencies():
#-----------------------------------------------------------------------
    subprocess.run(['pip','install','memoization'],check=True)
    subprocess.run(['pip','install','matplotlib'],check=True)

    # Dependencies with OS-specific BLAS
    if platform.system() == 'Windows':  
        # Install Numpy,SciPy, CVXopt linked to MKL
        subprocess.run(['pip','install','pipwin'],check=True)
        subprocess.run(['pipwin','install','numpy'],check=False)
        subprocess.run(['pipwin','install','scipy'],check=False)
        subprocess.run(['pipwin','install','cvxopt'],check=False)
    else:
        # Install Numpy,SciPy, CVXopt linked to OpenBLAS
        subprocess.run(['pip','install','numpy'],check=True)
        subprocess.run(['pip','install','scipy'],check=True)
        subprocess.run(['pip','install','cvxopt'],check=True)

    subprocess.run(['pip','install','numdifftools'],check=True)
    subprocess.run(['pip','install','tqdm'],check=True)
    subprocess.run(['pip','install','joblib'],check=True)
#-----------------------------------------------------------------------    
````
Since ``pip`` is called without the ``--user`` flag, the installation fails due to the lack of privilege to install dependencies system-wide. 

The easiest fix is to install DeerLab dependencies only at user-level not system-wide, e.g.
````python
subprocess.run(['pip','--user','install','memoization'],check=True)
```` 
but maybe there is a more elegant way to do this.

**Comment by mtessmer** [comment]
You should be using virtual environments on a cluster for any python project. This is not unique to DeerLab.

**Comment by luisfabib** [comment]
I am aware of that, however, in this cluster they recommend the direct installation of packages without a virtual environment. So users without much Python expertise stumbled upon this when following the cluster documentation.  

This might also be a problem in IT systems where users have limited privileges on their office computers.

**Comment by mtessmer** [comment]
You should probably just let pip handle (non-pipwin) dependencies instead of explicitly installing them.
