### ISSUE TITLE
bug with scales after 'fitsignal'

### ISSUE THREAD

**Issue by ritsch-i** [JeschkeLab/DeerLab#53]
Hi, I upgraded to DeerLab 0.12.0, and (as it mentions in the release notes) there are changes in how the fit output is now saved in terms of model scaling. However, the release mode don't say, how the final output is now scaled exactly (would be nice, because I had to adjust all my plot files accordingly...). And I think there is also a bug, because the scaling is differnet, when I used `fitsignal' with free distribtution or with model fit
In oder to get all lines on top of each other I need to scale differnt outputs differently, e.g.: 

````
plt.plot(t,V/deerfit[i].scale,'.b')#/deerfit[i].scale
plt.plot(t,deerfit[i].V,color='r') # free distribution
plt.plot(t,deerfit_gauss[i].V/deerfit[i].scale,color='k')# gauss model
````

**Comment by luisfabib** [comment]
There is indeed a discrepancy in how the signal scales are reported after `fitsignal`. The fully parametric mode returns `fit.V` with the scale of the experimental data, while the non-parametric modes return `fit.V` scaled down by `fit.scale`. 

Here is a MWE displaying this: 
```` python
import numpy as np 
import deerlab as dl
import matplotlib.pyplot as plt

t = np.linspace(-0.3,5,200)
r = np.linspace(1,5,200)
P = dl.dd_gauss(r,[3.5,0.3])
K = dl.dipolarkernel(t,r,0.3,dl.bg_hom3d(t,50,0.3))
V = K@P + dl.whitegaussnoise(t,0.01,seed=1)
V = V*1.4e6

deerfit = dl.fitsignal(V,t,r)
deerfit_gauss = dl.fitsignal(V,t,r,dl.dd_gauss)

plt.figure()
plt.plot(t,V,'.b')
plt.plot(t,deerfit.V,color='r') # snlls - mode
plt.plot(t,deerfit_gauss.V,color='k')  # fitparamodel - mode
plt.show()

t = np.linspace(-0.3,5,200)
r = np.linspace(1,5,200)
P = dl.dd_gauss(r,[3.5,0.3])
K = dl.dipolarkernel(t,r)
V = K@P + dl.whitegaussnoise(t,0.01,seed=1)
V = V*1.4e6

deerfit = dl.fitsignal(V,t,r,'P',None,None)
deerfit_gauss = dl.fitsignal(V,t,r,dl.dd_gauss,None,None)

plt.figure()
plt.plot(t,V,'.b')
plt.plot(t,deerfit.V,color='r') # fitregmodel - mode
plt.plot(t,deerfit_gauss.V,color='k') # fitparamodel - mode
plt.show()
````
