### ISSUE TITLE
Separate plotting from fitsignal

### ISSUE THREAD

**Issue by stestoll** [JeschkeLab/DeerLab#7]
Currently, `fitsignal` contains a function for plotting the fit result, which can be called via the `display` keyword.

I think it should be possible to put a fit result again (for example, after loading it from a stored file) without having to rerun the fit.

This means the API should provide a separate plotting function.

**Comment by luisfabib** [comment]
Yes, such a function is already under production. I was not sure whether to include it for 0.10.0.
