### ISSUE TITLE
Deerload 2D dataset dimension mapping

### ISSUE THREAD

**Issue by laenan8466** [JeschkeLab/DeerLab#82]
Hey,
I encounter a problem using deerload. Using this script

```python
dataImport = dict() # introduce as dictionary
dataImport['xyAxisArray'],dataImport['intensity'],dataImport['parameters'] = dl.deerload(filepath,full_output=True)
```
I get returned the correct data. When taking the xyAxisArray apart I receive the correct axises.
The dimension of the intensity array matches, but the values seem to be populated the wrong direction. So my data get shiftet with every scan (here time vs scan vise).
Data is included for testing, working on a fix right now.

[20200621_DB261_theta-spatial.zip](https://github.com/JeschkeLab/DeerLab/files/6061987/20200621_DB261_theta-spatial.zip)

**Comment by laenan8466** [comment]
Fount the error for my case:
in `deerload.py`, line 210:

```python
    if nz == 1:
        data = data.reshape(ny,nx)
```
I had to change the order of the arguments in the `reshape` command.
Tested this for only one dataset. Could s.o. check this for more datasets? I can create a pull request, if this is the solution.

**Comment by luisfabib** [comment]
Thanks for the quick diagnosis! You can open a PR if you want, and we will move the discussion and review of the fix there. I will also look deeper into the problem whether it is something general or specific to your dataset.
