### ISSUE TITLE
Bug: FitResult.plot doesn't scale all data.

### ISSUE THREAD

**Issue by laenan8466** [JeschkeLab/DeerLab#84]
The very basic example was used and only the Vexp was multiplied by 1000 to imitate experimental data. This results in a wrong plot (fit is in height of Vexp and datapoints are scaled to one).
This could be connected to #74 .

Example code:
```python
import numpy as np
import matplotlib.pyplot as plt
import deerlab as dl

t = np.linspace(-0.1,4,250)        # time axis, µs
r = np.linspace(1.5,6,len(t))      # distance axis, ns
param = [3, 0.1, 0.2, 3.5, 0.1, 0.65, 3.8, 0.05, 0.15] # parameters for three-Gaussian model
P = dl.dd_gauss3(r,param)          # model distance distribution
lam = 0.5                          # modulation depth
B = dl.bg_hom3d(t,300,lam)         # background decay
K = dl.dipolarkernel(t,r,lam,B)    # kernel matrix
Vexp = (K@P + dl.whitegaussnoise(t,0.01,seed=0))*1000

fit = dl.fitsignal(Vexp,t,r,'P',dl.bg_hom3d,dl.ex_4pdeer)
fit.plot()
```

Output graphic:
![grafik](https://user-images.githubusercontent.com/21331242/109531735-90645e00-7ab8-11eb-8d86-4f9e3578cf21.png)

**Comment by luisfabib** [comment]
This issue has been solved in #78 (pending review and merging).

**Comment by laenan8466** [comment]
Doh, havn't seen that. Sorry. Only searched the issues.

**Comment by luisfabib** [comment]
@laenan8466 No worries ;)
