### ISSUE TITLE
Rename fitsignal 

### ISSUE THREAD

**Issue by stestoll** [JeschkeLab/DeerLab#93]
Rename `fitsignal` to `fitmodel`.

Reasons:
1. Correct terminology. It fits the model to the signal, and not vice versa.
2. Function name consistency. We already have other `fit*model` functions.

Any counter-arguments?

**Comment by luisfabib** [comment]
I agree on both 1. and 2, for the sake of correctness and consistency we should change this, 

My question is whether we should rename it to `fitmodel` or something else. `fitmodel` might be a too generic name as it implies that any kind of model can be fitted. This is not true as in its core, `fitsignal` has a very defined hard-coded model (dipolar signals). Maybe something like `fitdipolarmodel` or shorter `fitdipmod` would be more appropriate.

**Comment by stestoll** [comment]
That's too tedious. It should be clear that this function fits dipolar models, since it is part of DeerLab.

What about just `fit`? This would set it nicely apart from `fitparamodel` etc.

**Comment by luisfabib** [comment]
I am also OK with `fit`. It will surely simplify scripts.

**Comment by stestoll** [comment]
Let's use `fit` then.

**Comment by luisfabib** [comment]
I just realized a downside of just calling it `fit`. We usually call our fit functions outputs `fit`. So this would clash with a function being called `fit = fit()`.

**Comment by stestoll** [comment]
That works.
